export interface HoroscopeData {
  sign: string;
  symbol: string;
  dateRange: string;
  element: string;
  ruling: string;
  today: string;
  love: string;
  career: string;
  health: string;
  luckyNumber: number;
  luckyColor: string;
  mood: string;
}

export const horoscopes: Record<string, HoroscopeData> = {
  Aries: {
    sign: 'Aries',
    symbol: '♈',
    dateRange: 'March 21 – April 19',
    element: 'Fire',
    ruling: 'Mars',
    today: `The cosmos ignite your pioneering spirit today, Aries. A surge of bold energy courses through you, urging you to take decisive action on a plan you have long been contemplating. The Sun forms a powerful trine with your ruling planet Mars, amplifying your confidence and courage. Do not hesitate — the universe rewards those who act with conviction. A chance encounter could open unexpected doors in the afternoon hours. Trust your instincts; they are sharper than ever.`,
    love: `Passion runs high in your love life. Single Rams may feel an irresistible magnetic pull toward someone bold and mysterious. Partners will appreciate your fiery devotion today — plan something spontaneous to fan the flames.`,
    career: `Your leadership qualities shine brilliantly. Colleagues look to you for direction, and your ideas carry significant weight in any room you enter. A competitive opportunity may arise — seize it without hesitation.`,
    health: `Channel your abundant energy into vigorous physical activity. A morning run or high-intensity workout will set a triumphant tone for the day. Watch a tendency toward impatience; take a breath before reacting.`,
    luckyNumber: 9,
    luckyColor: 'Crimson Red',
    mood: 'Energetic',
  },
  Taurus: {
    sign: 'Taurus',
    symbol: '♉',
    dateRange: 'April 20 – May 20',
    element: 'Earth',
    ruling: 'Venus',
    today: `Venus, your celestial guardian, wraps today in a cloak of beauty and sensual delight, dear Taurus. Your appreciation for life's finer things is heightened — seek out art, music, or a lovingly prepared meal to nourish your soul. Financial matters come into sharper focus; a patient decision you made months ago begins to bear fruit. Ground yourself in gratitude and watch abundance flow naturally toward you.`,
    love: `Romantic connections deepen considerably today. You radiate a warm, irresistible magnetism that draws others close. Express affection through thoughtful gestures: a home-cooked meal, a heartfelt note, a tender touch.`,
    career: `Steady, methodical progress is your hallmark. A financial opportunity deserves careful scrutiny before you commit — your instinct for value is impeccable. Colleagues rely on your calm, stabilizing presence.`,
    health: `Pamper yourself intentionally. A luxurious bath with essential oils, gentle yoga, or a walk through nature will restore your equilibrium. Avoid overindulgence in rich foods, tempting as it may be.`,
    luckyNumber: 6,
    luckyColor: 'Emerald Green',
    mood: 'Serene',
  },
  Gemini: {
    sign: 'Gemini',
    symbol: '♊',
    dateRange: 'May 21 – June 20',
    element: 'Air',
    ruling: 'Mercury',
    today: `Your quicksilver mind is in overdrive today, Gemini, as Mercury sparks brilliant connections between seemingly unrelated ideas. Conversations crackle with wit and intellectual electricity — you are the most fascinating person in any room. Multiple opportunities present themselves simultaneously, and your greatest challenge is choosing which thread to follow. Embrace your duality: be both the dreamer and the analyst.`,
    love: `Words are your love language today, and you wield them with poetic precision. Flirtatious banter ignites something deeper; a simple text conversation could evolve into a profound heart-to-heart. Communication is the key to intimacy.`,
    career: `Your networking skills are unmatched right now. Reach out to old contacts and forge new alliances — a collaboration born today could prove remarkably fruitful. Writing, presenting, or negotiating will showcase your gifts.`,
    health: `Mental stimulation is excellent, but ground your restless mind with brief meditation breaks. Breathing exercises calm the nervous system and sharpen your already formidable focus.`,
    luckyNumber: 5,
    luckyColor: 'Sunshine Yellow',
    mood: 'Curious',
  },
  Cancer: {
    sign: 'Cancer',
    symbol: '♋',
    dateRange: 'June 21 – July 22',
    element: 'Water',
    ruling: 'Moon',
    today: `The Moon, your cosmic mother, floods you with heightened intuition and emotional depth today, dear Cancer. You feel the undercurrents of every situation with uncanny accuracy — trust those feelings without apology. Home and family call to you; tending your inner sanctuary brings profound peace. A creative project infused with personal meaning flourishes under this gentle, nurturing energy.`,
    love: `Your capacity for deep emotional connection is extraordinary today. Vulnerability is your superpower — sharing your true feelings dissolves barriers and invites profound intimacy. Nurture those you love with your characteristic warmth.`,
    career: `Your intuitive grasp of what colleagues and clients need makes you invaluable today. Behind-the-scenes work yields satisfying results. Trust your gut on a business decision that logic alone cannot resolve.`,
    health: `Emotional and physical health are intertwined for you. Journal your feelings, cook a nourishing meal, or spend time near water to replenish your spirit. Rest is sacred — honour your body's need for restoration.`,
    luckyNumber: 2,
    luckyColor: 'Silver',
    mood: 'Intuitive',
  },
  Leo: {
    sign: 'Leo',
    symbol: '♌',
    dateRange: 'July 23 – August 22',
    element: 'Fire',
    ruling: 'Sun',
    today: `The Sun blazes in your favour today, magnificent Leo, and the world cannot help but turn toward your radiant warmth. Your natural charisma is amplified to dazzling heights — step onto whatever stage life offers and shine without reservation. Creative self-expression reaches a peak; an artistic endeavour you pour your heart into will resonate deeply with others. Generosity returns to you threefold.`,
    love: `Romance is theatrical, passionate, and utterly unforgettable today. Grand gestures feel natural and entirely appropriate. A admirer watches from the wings, waiting for the right moment — your awareness is your invitation.`,
    career: `Leadership and visibility are your themes. Present your ideas boldly; the spotlight finds those who claim it with confidence. A moment of recognition you deserve is finally arriving — receive it with gracious dignity.`,
    health: `Your vitality is exceptional. Physical activity that lets you express yourself — dance, performance sports, martial arts — channels your solar energy beautifully. Heart health benefits from joyful exertion.`,
    luckyNumber: 1,
    luckyColor: 'Royal Gold',
    mood: 'Radiant',
  },
  Virgo: {
    sign: 'Virgo',
    symbol: '♍',
    dateRange: 'August 23 – September 22',
    element: 'Earth',
    ruling: 'Mercury',
    today: `Your analytical gifts reach their apex today, Virgo, as Mercury sharpens your already formidable mind to a razor's edge. Details others overlook reveal themselves to you in crystalline clarity — this precision will prove invaluable. A complex problem that has nagged at you finally yields to your methodical approach. Service to others brings you deep satisfaction; helping someone navigate a challenge is its own reward.`,
    love: `You show love through acts of devoted service, and today your thoughtfulness is especially apparent. Small, perfect gestures mean more than grand declarations. Allow yourself to receive care as graciously as you give it.`,
    career: `Meticulous execution of a detailed project earns well-deserved recognition. Your organisational talents transform chaos into elegant order. A health or wellness project benefits from your systematic approach.`,
    health: `Mind-body connection is your wellness theme. Nutrition, routine, and preventive care are areas where your natural tendencies align perfectly with vibrant health. A consistent sleep schedule amplifies your mental clarity.`,
    luckyNumber: 4,
    luckyColor: 'Forest Green',
    mood: 'Focused',
  },
  Libra: {
    sign: 'Libra',
    symbol: '♎',
    dateRange: 'September 23 – October 22',
    element: 'Air',
    ruling: 'Venus',
    today: `Harmony sings through every interaction today, graceful Libra, as Venus blesses your social sphere with beauty and diplomacy. Your gift for finding the perfect balance between opposing forces makes you an indispensable mediator and ally. Aesthetic choices — in your home, wardrobe, or creative work — are impeccably inspired. An important relationship reaches a meaningful milestone of mutual understanding.`,
    love: `Partnership is your natural element, and today it sparkles with particular brilliance. A conversation with someone special reaches a new level of honest, loving exchange. Beauty surrounds and enchants — plan a romantic outing somewhere visually stunning.`,
    career: `Your diplomatic finesse resolves a workplace tension that others have found intractable. Collaborative projects flourish under your fair-minded stewardship. Legal or contractual matters benefit from your balanced perspective.`,
    health: `Beauty rituals are genuinely therapeutic for you today — treat them as sacred practice. Balance active and restorative activities. Social connection and fresh air improve your overall sense of wellbeing.`,
    luckyNumber: 7,
    luckyColor: 'Soft Rose',
    mood: 'Harmonious',
  },
  Scorpio: {
    sign: 'Scorpio',
    symbol: '♏',
    dateRange: 'October 23 – November 21',
    element: 'Water',
    ruling: 'Pluto',
    today: `The depths of mystery and transformation beckon you today, powerful Scorpio. Pluto's penetrating influence reveals hidden truths that have eluded others — your instinct for what lies beneath the surface is unfailing. A psychological breakthrough transforms the way you understand a longstanding pattern in your life. Embrace change; you are the phoenix, and this is your moment of glorious regeneration.`,
    love: `Intensity defines your romantic encounters today. Soul-deep connection is the only kind that satisfies you, and the cosmos conspire to deliver exactly that. Trust is built through brave vulnerability — dare to go deeper than feels comfortable.`,
    career: `Research, investigation, and strategic planning are your domains of brilliance. You uncover what others conceal — use this power ethically and your reputation for insight becomes legendary. Financial strategy sharpens considerably.`,
    health: `Emotional processing is physical health for a Scorpio. Release suppressed feelings through cathartic exercise, shadow journaling, or therapy. Detox practices — both literal and metaphorical — are powerfully effective today.`,
    luckyNumber: 8,
    luckyColor: 'Deep Crimson',
    mood: 'Intense',
  },
  Sagittarius: {
    sign: 'Sagittarius',
    symbol: '♐',
    dateRange: 'November 22 – December 21',
    element: 'Fire',
    ruling: 'Jupiter',
    today: `Jupiter's expansive blessing carries you toward the far horizons of possibility today, adventurous Sagittarius. Your philosophical mind hungers for truth, wisdom, and experiences that stretch the boundaries of what you thought possible. Travel, higher learning, or a meaningful conversation with someone from a different culture ignites your eternal flame of curiosity. Freedom is your birthright — honour it.`,
    love: `Your irresistible enthusiasm and infectious laughter attract admirers from unexpected directions. A relationship deepens through shared adventure or intellectual exploration. Freedom must be mutual — honour your partner's independence as fiercely as your own.`,
    career: `Publishing, teaching, travel, or cross-cultural ventures are brilliantly favoured. Your optimism and big-picture thinking inspire your team to dream larger. A distant opportunity deserves serious consideration.`,
    health: `Outdoor adventure and physical exploration are your ideal medicine. Hiking, riding, or any activity that combines movement with discovery nurtures your spirited nature. Watch a tendency to overextend — even archers must rest their bow.`,
    luckyNumber: 3,
    luckyColor: 'Royal Purple',
    mood: 'Adventurous',
  },
  Capricorn: {
    sign: 'Capricorn',
    symbol: '♑',
    dateRange: 'December 22 – January 19',
    element: 'Earth',
    ruling: 'Saturn',
    today: `Saturn, your steadfast patron, rewards your disciplined patience with tangible progress today, ambitious Capricorn. The mountain you have been steadily climbing reveals a stunning new vista — the effort was entirely worth it. Authority figures and senior colleagues recognise your exceptional competence. Long-term plans solidify into concrete reality; the structures you have built with such care now support a grander vision.`,
    love: `You express love through loyalty, reliability, and practical acts of devotion. Today, allowing vulnerability softens your formidable exterior and creates space for genuine intimacy. A partner sees the tender heart beneath the composed exterior.`,
    career: `Professional achievement is especially highlighted. A project you have invested significant effort in receives recognition from the highest levels. Your reputation for integrity and excellence opens a significant door.`,
    health: `Structural wellbeing — bones, joints, posture — benefits from mindful attention. Incorporate stretching, strength training, and adequate sleep into your ambitious schedule. Rest is not weakness; it is strategic recovery.`,
    luckyNumber: 10,
    luckyColor: 'Charcoal Grey',
    mood: 'Determined',
  },
  Aquarius: {
    sign: 'Aquarius',
    symbol: '♒',
    dateRange: 'January 20 – February 18',
    element: 'Air',
    ruling: 'Uranus',
    today: `Uranus, the great awakener, crackles through your consciousness today, visionary Aquarius, delivering flashes of genius that astonish even you. Your humanitarian ideals find a powerful channel for expression — a cause you believe in gains meaningful momentum through your involvement. Unconventional solutions to collective problems emerge from your brilliantly original mind. The future you envision is closer than it appears.`,
    love: `Friendship is the foundation of your deepest romantic connections, and today that bond strengthens beautifully. Intellectual compatibility and shared values are irresistibly attractive to you. Celebrate what makes your relationship delightfully unique.`,
    career: `Technology, innovation, social change, and humanitarian endeavours are your zones of genius. An eccentric or unconventional approach achieves what traditional methods cannot. Your network is your net worth — nurture it.`,
    health: `Mental stimulation is as vital as physical activity for your wellbeing. Engage in activities that challenge your extraordinary mind while also moving your body — cycling while listening to a fascinating podcast, for example.`,
    luckyNumber: 11,
    luckyColor: 'Electric Blue',
    mood: 'Innovative',
  },
  Pisces: {
    sign: 'Pisces',
    symbol: '♓',
    dateRange: 'February 19 – March 20',
    element: 'Water',
    ruling: 'Neptune',
    today: `Neptune, your mystical ruler, dissolves the veil between worlds today, ethereal Pisces, allowing extraordinary inspiration to flow through you like a celestial river. Your intuition is so finely tuned that you perceive what others cannot even begin to sense. Creative and spiritual pursuits reach transcendent heights — music, poetry, painting, prayer, or meditation opens portals to profound beauty. Compassion for all beings fills your luminous heart.`,
    love: `Your romantic nature reaches its most enchanting expression. A dream-like encounter carries the quality of genuine magic — remain open to the miraculous. Love, for you, is always sacred; honour that truth without apology.`,
    career: `Creative, healing, spiritual, and artistic work flourishes magnificently. Your empathic gifts make you an exceptional counsellor, healer, or artist. Trust inspired hunches over purely logical analysis today.`,
    health: `Spiritual practice is the cornerstone of your physical wellbeing. Meditation near water, restorative yoga, or simply floating in a warm bath restores your sensitive nervous system. Guard your energy carefully — emotional boundaries protect your vitality.`,
    luckyNumber: 12,
    luckyColor: 'Sea Blue',
    mood: 'Dreamy',
  },
};

export function getHoroscope(sign: string): HoroscopeData | null {
  return horoscopes[sign] || null;
}

export const ALL_SIGNS = Object.keys(horoscopes);
