export interface HoroscopeData {
  sign: string;
  symbol: string;
  dateRange: string;
  element: string;
  ruling: string;
  today: string;
  love: string;
  career: string;
  health: string;
  luckyNumber: number;
  luckyColor: string;
  mood: string;
}

export const horoscopes: Record<string, HoroscopeData> = {
  Aries: {
    sign: 'Aries',
    symbol: '♈',
    dateRange: 'March 21 – April 19',
    element: 'Fire',
    ruling: 'Mars',
    today: `The cosmos ignite your pioneering spirit today, Aries. A surge of bold energy courses through you, urging you to take decisive action on a plan you have long been contemplating. The Sun forms a powerful trine with your ruling planet Mars, amplifying your confidence and courage. Do not hesitate — the universe rewards those who act with conviction. A chance encounter could open unexpected doors in the afternoon hours. Trust your instincts; they are sharper than ever.`,
    love: `Passion runs high in your love life. Single Rams may feel an irresistible magnetic pull toward someone bold and mysterious. Partners will appreciate your fiery devotion today — plan something spontaneous to fan the flames.`,
    career: `Your leadership qualities shine brilliantly. Colleagues look to you for direction, and your ideas carry significant weight in any room you enter. A competitive opportunity may arise — seize it without hesitation.`,
    health: `Channel your abundant energy into vigorous physical activity. A morning run or high-intensity workout will set a triumphant tone for the day. Watch a tendency toward impatience; take a breath before reacting.`,
    luckyNumber: 9,
    luckyColor: 'Crimson Red',
    mood: 'Energetic',
  },
  Taurus: {
    sign: 'Taurus',
    symbol: '♉',
    dateRange: 'April 20 – May 20',
    element: 'Earth',
    ruling: 'Venus',
    today: `Venus, your celestial guardian, wraps today in a cloak of beauty and sensual delight, dear Taurus. Your appreciation for life's finer things is heightened — seek out art, music, or a lovingly prepared meal to nourish your soul. Financial matters come into sharper focus; a patient decision you made months ago begins to bear fruit. Ground yourself in gratitude and watch abundance flow naturally toward you.`,
    love: `Romantic connections deepen considerably today. You radiate a warm, irresistible magnetism that draws others close. Express affection through thoughtful gestures: a home-cooked meal, a heartfelt note, a tender touch.`,
    career: `Steady, methodical progress is your hallmark. A financial opportunity deserves careful scrutiny before you commit — your instinct for value is impeccable. Colleagues rely on your calm, stabilizing presence.`,
    health: `Pamper yourself intentionally. A luxurious bath with essential oils, gentle yoga, or a walk through nature will restore your equilibrium. Avoid overindulgence in rich foods, tempting as it may be.`,
    luckyNumber: 6,
    luckyColor: 'Emerald Green',
    mood: 'Serene',
  },
  Gemini: {
    sign: 'Gemini',
    symbol: '♊',
    dateRange: 'May 21 – June 20',
    element: 'Air',
    ruling: 'Mercury',
    today: `Your quicksilver mind is in overdrive today, Gemini, as Mercury sparks brilliant connections between seemingly unrelated ideas. Conversations crackle with wit and intellectual electricity — you are the most fascinating person in any room. Multiple opportunities present themselves simultaneously, and your greatest challenge is choosing which thread to follow. Embrace your duality: be both the dreamer and the analyst.`,
    love: `Words are your love language today, and you wield them with poetic precision. Flirtatious banter ignites something deeper; a simple text conversation could evolve into a profound heart-to-heart. Communication is the key to intimacy.`,
    career: `Your networking skills are unmatched right now. Reach out to old contacts and forge new alliances — a collaboration born today could prove remarkably fruitful. Writing, presenting, or negotiating will showcase your gifts.`,
    health: `Mental stimulation is excellent, but ground your restless mind with brief meditation breaks. Breathing exercises calm the nervous system and sharpen your already formidable focus.`,
    luckyNumber: 5,
    luckyColor: 'Sunshine Yellow',
    mood: 'Curious',
  },
  Cancer: {
    sign: 'Cancer',
    symbol: '♋',
    dateRange: 'June 21 – July 22',
    element: 'Water',
    ruling: 'Moon',
    today: `The Moon, your cosmic mother, floods you with heightened intuition and emotional depth today, dear Cancer. You feel the undercurrents of every situation with uncanny accuracy — trust those feelings without apology. Home and family call to you; tending your inner sanctuary brings profound peace. A creative project infused with personal meaning flourishes under this gentle, nurturing energy.`,
    love: `Your capacity for deep emotional connection is extraordinary today. Vulnerability is your superpower — sharing your true feelings dissolves barriers and invites profound intimacy. Nurture those you love with your characteristic warmth.`,
    career: `Your intuitive grasp of what colleagues and clients need makes you invaluable today. Behind-the-scenes work yields satisfying results. Trust your gut on a business decision that logic alone cannot resolve.`,
    health: `Emotional and physical health are intertwined for you. Journal your feelings, cook a nourishing meal, or spend time near water to replenish your spirit. Rest is sacred — honour your body's need for restoration.`,
    luckyNumber: 2,
    luckyColor: 'Silver',
    mood: 'Intuitive',
  },
  Leo: {
    sign: 'Leo',
    symbol: '♌',
    dateRange: 'July 23 – August 22',
    element: 'Fire',
    ruling: 'Sun',
    today: `The Sun blazes in your favour today, magnificent Leo, and the world cannot help but turn toward your radiant warmth. Your natural charisma is amplified to dazzling heights — step onto whatever stage life offers and shine without reservation. Creative self-expression reaches a peak; an artistic endeavour you pour your heart into will resonate deeply with others. Generosity returns to you threefold.`,
    love: `Romance is theatrical, passionate, and utterly unforgettable today. Grand gestures feel natural and entirely appropriate. A admirer watches from the wings, waiting for the right moment — your awareness is your invitation.`,
    career: `Leadership and visibility are your themes. Present your ideas boldly; the spotlight finds those who claim it with confidence. A moment of recognition you deserve is finally arriving — receive it with gracious dignity.`,
    health: `Your vitality is exceptional. Physical activity that lets you express yourself — dance, performance sports, martial arts — channels your solar energy beautifully. Heart health benefits from joyful exertion.`,
    luckyNumber: 1,
    luckyColor: 'Royal Gold',
    mood: 'Radiant',
  },
  Virgo: {
    sign: 'Virgo',
    symbol: '♍',
    dateRange: 'August 23 – September 22',
    element: 'Earth',
    ruling: 'Mercury',
    today: `Your analytical gifts reach their apex today, Virgo, as Mercury sharpens your already formidable mind to a razor's edge. Details others overlook reveal themselves to you in crystalline clarity — this precision will prove invaluable. A complex problem that has nagged at you finally yields to your methodical approach. Service to others brings you deep satisfaction; helping someone navigate a challenge is its own reward.`,
    love: `You show love through acts of devoted service, and today your thoughtfulness is especially apparent. Small, perfect gestures mean more than grand declarations. Allow yourself to receive care as graciously as you give it.`,
    career: `Meticulous execution of a detailed project earns well-deserved recognition. Your organisational talents transform chaos into elegant order. A health or wellness project benefits from your systematic approach.`,
    health: `Mind-body connection is your wellness theme. Nutrition, routine, and preventive care are areas where your natural tendencies align perfectly with vibrant health. A consistent sleep schedule amplifies your mental clarity.`,
    luckyNumber: 4,
    luckyColor: 'Forest Green',
    mood: 'Focused',
  },
  Libra: {
    sign: 'Libra',
    symbol: '♎',
    dateRange: 'September 23 – October 22',
    element: 'Air',
    ruling: 'Venus',
    today: `Harmony sings through every interaction today, graceful Libra, as Venus blesses your social sphere with beauty and diplomacy. Your gift for finding the perfect balance between opposing forces makes you an indispensable mediator and ally. Aesthetic choices — in your home, wardrobe, or creative work — are impeccably inspired. An important relationship reaches a meaningful milestone of mutual understanding.`,
    love: `Partnership is your natural element, and today it sparkles with particular brilliance. A conversation with someone special reaches a new level of honest, loving exchange. Beauty surrounds and enchants — plan a romantic outing somewhere visually stunning.`,
    career: `Your diplomatic finesse resolves a workplace tension that others have found intractable. Collaborative projects flourish under your fair-minded stewardship. Legal or contractual matters benefit from your balanced perspective.`,
    health: `Beauty rituals are genuinely therapeutic for you today — treat them as sacred practice. Balance active and restorative activities. Social connection and fresh air improve your overall sense of wellbeing.`,
    luckyNumber: 7,
    luckyColor: 'Soft Rose',
    mood: 'Harmonious',
  },
  Scorpio: {
    sign: 'Scorpio',
    symbol: '♏',
    dateRange: 'October 23 – November 21',
    element: 'Water',
    ruling: 'Pluto',
    today: `The depths of mystery and transformation beckon you today, powerful Scorpio. Pluto's penetrating influence reveals hidden truths that have eluded others — your instinct for what lies beneath the surface is unfailing. A psychological breakthrough transforms the way you understand a longstanding pattern in your life. Embrace change; you are the phoenix, and this is your moment of glorious regeneration.`,
    love: `Intensity defines your romantic encounters today. Soul-deep connection is the only kind that satisfies you, and the cosmos conspire to deliver exactly that. Trust is built through brave vulnerability — dare to go deeper than feels comfortable.`,
    career: `Research, investigation, and strategic planning are your domains of brilliance. You uncover what others conceal — use this power ethically and your reputation for insight becomes legendary. Financial strategy sharpens considerably.`,
    health: `Emotional processing is physical health for a Scorpio. Release suppressed feelings through cathartic exercise, shadow journaling, or therapy. Detox practices — both literal and metaphorical — are powerfully effective today.`,
    luckyNumber: 8,
    luckyColor: 'Deep Crimson',
    mood: 'Intense',
  },
  Sagittarius: {
    sign: 'Sagittarius',
    symbol: '♐',
    dateRange: 'November 22 – December 21',
    element: 'Fire',
    ruling: 'Jupiter',
    today: `Jupiter's expansive blessing carries you toward the far horizons of possibility today, adventurous Sagittarius. Your philosophical mind hungers for truth, wisdom, and experiences that stretch the boundaries of what you thought possible. Travel, higher learning, or a meaningful conversation with someone from a different culture ignites your eternal flame of curiosity. Freedom is your birthright — honour it.`,
    love: `Your irresistible enthusiasm and infectious laughter attract admirers from unexpected directions. A relationship deepens through shared adventure or intellectual exploration. Freedom must be mutual — honour your partner's independence as fiercely as your own.`,
    career: `Publishing, teaching, travel, or cross-cultural ventures are brilliantly favoured. Your optimism and big-picture thinking inspire your team to dream larger. A distant opportunity deserves serious consideration.`,
    health: `Outdoor adventure and physical exploration are your ideal medicine. Hiking, riding, or any activity that combines movement with discovery nurtures your spirited nature. Watch a tendency to overextend — even archers must rest their bow.`,
    luckyNumber: 3,
    luckyColor: 'Royal Purple',
    mood: 'Adventurous',
  },
  Capricorn: {
    sign: 'Capricorn',
    symbol: '♑',
    dateRange: 'December 22 – January 19',
    element: 'Earth',
    ruling: 'Saturn',
    today: `Saturn, your steadfast patron, rewards your disciplined patience with tangible progress today, ambitious Capricorn. The mountain you have been steadily climbing reveals a stunning new vista — the effort was entirely worth it. Authority figures and senior colleagues recognise your exceptional competence. Long-term plans solidify into concrete reality; the structures you have built with such care now support a grander vision.`,
    love: `You express love through loyalty, reliability, and practical acts of devotion. Today, allowing vulnerability softens your formidable exterior and creates space for genuine intimacy. A partner sees the tender heart beneath the composed exterior.`,
    career: `Professional achievement is especially highlighted. A project you have invested significant effort in receives recognition from the highest levels. Your reputation for integrity and excellence opens a significant door.`,
    health: `Structural wellbeing — bones, joints, posture — benefits from mindful attention. Incorporate stretching, strength training, and adequate sleep into your ambitious schedule. Rest is not weakness; it is strategic recovery.`,
    luckyNumber: 10,
    luckyColor: 'Charcoal Grey',
    mood: 'Determined',
  },
  Aquarius: {
    sign: 'Aquarius',
    symbol: '♒',
    dateRange: 'January 20 – February 18',
    element: 'Air',
    ruling: 'Uranus',
    today: `Uranus, the great awakener, crackles through your consciousness today, visionary Aquarius, delivering flashes of genius that astonish even you. Your humanitarian ideals find a powerful channel for expression — a cause you believe in gains meaningful momentum through your involvement. Unconventional solutions to collective problems emerge from your brilliantly original mind. The future you envision is closer than it appears.`,
    love: `Friendship is the foundation of your deepest romantic connections, and today that bond strengthens beautifully. Intellectual compatibility and shared values are irresistibly attractive to you. Celebrate what makes your relationship delightfully unique.`,
    career: `Technology, innovation, social change, and humanitarian endeavours are your zones of genius. An eccentric or unconventional approach achieves what traditional methods cannot. Your network is your net worth — nurture it.`,
    health: `Mental stimulation is as vital as physical activity for your wellbeing. Engage in activities that challenge your extraordinary mind while also moving your body — cycling while listening to a fascinating podcast, for example.`,
    luckyNumber: 11,
    luckyColor: 'Electric Blue',
    mood: 'Innovative',
  },
  Pisces: {
    sign: 'Pisces',
    symbol: '♓',
    dateRange: 'February 19 – March 20',
    element: 'Water',
    ruling: 'Neptune',
    today: `Neptune, your mystical ruler, dissolves the veil between worlds today, ethereal Pisces, allowing extraordinary inspiration to flow through you like a celestial river. Your intuition is so finely tuned that you perceive what others cannot even begin to sense. Creative and spiritual pursuits reach transcendent heights — music, poetry, painting, prayer, or meditation opens portals to profound beauty. Compassion for all beings fills your luminous heart.`,
    love: `Your romantic nature reaches its most enchanting expression. A dream-like encounter carries the quality of genuine magic — remain open to the miraculous. Love, for you, is always sacred; honour that truth without apology.`,
    career: `Creative, healing, spiritual, and artistic work flourishes magnificently. Your empathic gifts make you an exceptional counsellor, healer, or artist. Trust inspired hunches over purely logical analysis today.`,
    health: `Spiritual practice is the cornerstone of your physical wellbeing. Meditation near water, restorative yoga, or simply floating in a warm bath restores your sensitive nervous system. Guard your energy carefully — emotional boundaries protect your vitality.`,
    luckyNumber: 12,
    luckyColor: 'Sea Blue',
    mood: 'Dreamy',
  },
};

const horoscopesHi: Record<string, HoroscopeData> = {
  Aries: {
    sign: 'Aries', symbol: '♈', dateRange: '21 मार्च – 19 अप्रैल', element: 'अग्नि', ruling: 'मंगल',
    today: `आज ब्रह्मांड आपकी अग्नि को प्रज्वलित कर रहा है, मेष राशि। सूर्य और मंगल का शक्तिशाली योग आपके साहस और आत्मविश्वास को नई ऊँचाइयों तक ले जाता है। जो निर्णय आप लंबे समय से टाल रहे थे, आज उसे लेने का सही समय है। दोपहर में एक अप्रत्याशित मुलाकात नए अवसरों के द्वार खोल सकती है। अपनी अंतरात्मा की आवाज़ सुनें — वह आज पहले से कहीं अधिक स्पष्ट है।`,
    love: `प्रेम में आज अद्भुत ऊर्जा है। अविवाहित मेष जातक किसी साहसी और रहस्यमयी व्यक्ति की ओर आकर्षित हो सकते हैं। अपने साथी को एक अप्रत्याशित आश्चर्य दें — यह रिश्ते में नई आग लगा देगा।`,
    career: `आपके नेतृत्व गुण आज चमक रहे हैं। सहकर्मी आपसे मार्गदर्शन मांग रहे हैं। कोई प्रतिस्पर्धी अवसर सामने आए तो बिना झिझक आगे बढ़ें।`,
    health: `आज भरपूर शारीरिक ऊर्जा है — इसे व्यायाम में लगाएं। सुबह की दौड़ या उच्च-तीव्रता कसरत आपके पूरे दिन को शानदार बना देगी।`,
    luckyNumber: 9, luckyColor: 'लाल', mood: 'ऊर्जावान',
  },
  Taurus: {
    sign: 'Taurus', symbol: '♉', dateRange: '20 अप्रैल – 20 मई', element: 'पृथ्वी', ruling: 'शुक्र',
    today: `शुक्र ग्रह आज आपके जीवन को सौंदर्य और सुख से भर रहा है, वृष राशि। कला, संगीत या स्वादिष्ट भोजन में अपनी आत्मा को तृप्त करें। महीनों पहले किया गया एक धैर्यपूर्ण निर्णय आज फल देने लगा है। कृतज्ञता में जीएं और देखें कैसे समृद्धि स्वाभाविक रूप से आपकी ओर बहती है।`,
    love: `आज आप एक गर्म, अप्रतिरोध्य आकर्षण से भरे हैं। प्रेम को छोटे-छोटे विचारशील कार्यों से व्यक्त करें — घर का बना खाना, हृदय से लिखा एक पत्र।`,
    career: `स्थिर और पद्धतिबद्ध प्रगति आपकी पहचान है। किसी वित्तीय अवसर की सावधानी से जांच करें — आपकी मूल्य परखने की क्षमता अद्वितीय है।`,
    health: `आज खुद को प्यार से पोषित करें। सुगंधित तेल के साथ स्नान, हल्का योग या प्रकृति में सैर आपकी ऊर्जा को पुनर्जीवित करेगी।`,
    luckyNumber: 6, luckyColor: 'हरा', mood: 'शांत',
  },
  Gemini: {
    sign: 'Gemini', symbol: '♊', dateRange: '21 मई – 20 जून', element: 'वायु', ruling: 'बुध',
    today: `आज आपका तीव्र बुद्धि-मन असंबंधित विचारों के बीच अद्भुत संबंध खोज रहा है, मिथुन राशि। बातचीत बौद्धिक ऊर्जा से चमक रही है — आप किसी भी कमरे में सबसे रोचक व्यक्ति हैं। कई अवसर एक साथ आ सकते हैं — सबसे प्रेरणादायक धागे को पकड़ें।`,
    love: `आज शब्द आपकी प्रेम भाषा हैं। एक साधारण बातचीत गहरे हृदय-संवाद में बदल सकती है। संचार ही अंतरंगता की कुंजी है।`,
    career: `आपकी नेटवर्किंग क्षमता अभी बेमिसाल है। पुराने संपर्कों से जुड़ें — आज जन्मा सहयोग भविष्य में बेहद फलदायी साबित हो सकता है।`,
    health: `मानसिक उत्तेजना बहुत अच्छी है, लेकिन थोड़े ध्यान से अपने चंचल मन को स्थिर करें। श्वास अभ्यास आपकी एकाग्रता बढ़ाएगा।`,
    luckyNumber: 5, luckyColor: 'पीला', mood: 'जिज्ञासु',
  },
  Cancer: {
    sign: 'Cancer', symbol: '♋', dateRange: '21 जून – 22 जुलाई', element: 'जल', ruling: 'चंद्रमा',
    today: `चंद्रमा आज आपकी अंतर्ज्ञान शक्ति को असाधारण रूप से तीव्र कर रहा है, कर्क राशि। आप हर परिस्थिति की अंतर्धारा को गहराई से महसूस कर सकते हैं — इन भावनाओं पर भरोसा करें। घर और परिवार आज आपको सबसे अधिक शांति देंगे।`,
    love: `आज आपकी गहरी भावनात्मक संवेदनशीलता प्रेम में अद्भुत गहराई लाती है। अपनी सच्ची भावनाएं साझा करें — यह सभी दीवारें गिरा देती हैं।`,
    career: `सहकर्मियों और ग्राहकों की ज़रूरतों को समझने की आपकी सहज क्षमता आज अमूल्य है। किसी व्यावसायिक निर्णय पर अपनी अंतरात्मा की सुनें।`,
    health: `भावनात्मक और शारीरिक स्वास्थ्य आपके लिए आपस में जुड़े हैं। डायरी लिखें, पोषक भोजन बनाएं, या पानी के पास समय बिताएं।`,
    luckyNumber: 2, luckyColor: 'चांदी', mood: 'सहज ज्ञानी',
  },
  Leo: {
    sign: 'Leo', symbol: '♌', dateRange: '23 जुलाई – 22 अगस्त', element: 'अग्नि', ruling: 'सूर्य',
    today: `आज सूर्य आपके पक्ष में चमक रहा है, सिंह राशि। आपका प्राकृतिक करिश्मा अपने उच्चतम स्तर पर है — बिना झिझक अपना मंच संभालें। रचनात्मक अभिव्यक्ति आज अपने शिखर पर है। उदारता आपके पास तीन गुना होकर लौटती है।`,
    love: `आज प्रेम नाटकीय, जोशीला और पूरी तरह अविस्मरणीय है। भव्य इशारे स्वाभाविक लगते हैं। कोई प्रशंसक पंखों में खड़ा है, सही पल की प्रतीक्षा में।`,
    career: `नेतृत्व और दृश्यता आज आपके विषय हैं। अपने विचारों को साहसपूर्वक प्रस्तुत करें। जिस सम्मान के आप हकदार हैं वह अंततः आ रहा है।`,
    health: `आपकी जीवनशक्ति असाधारण है। नृत्य, मार्शल आर्ट जैसी गतिविधियाँ आपकी सौर ऊर्जा को सुंदरता से प्रवाहित करती हैं।`,
    luckyNumber: 1, luckyColor: 'सोना', mood: 'तेजस्वी',
  },
  Virgo: {
    sign: 'Virgo', symbol: '♍', dateRange: '23 अगस्त – 22 सितंबर', element: 'पृथ्वी', ruling: 'बुध',
    today: `आज बुध आपके विश्लेषणात्मक उपहारों को उनके शिखर पर ले जाता है, कन्या राशि। जो विवरण दूसरे नज़रअंदाज़ करते हैं वे आपको स्फटिक स्पष्टता से दिखते हैं। एक जटिल समस्या जो आपको परेशान कर रही थी, अंततः आपके पद्धतिबद्ध दृष्टिकोण के सामने झुकती है।`,
    love: `आप सेवा के माध्यम से प्रेम दिखाते हैं, और आज आपकी विचारशीलता विशेष रूप से स्पष्ट है। छोटे, परिपूर्ण इशारे भव्य घोषणाओं से अधिक मायने रखते हैं।`,
    career: `एक विस्तृत परियोजना का सावधानीपूर्वक निष्पादन अच्छी-खासी पहचान दिलाता है। आपकी संगठनात्मक प्रतिभा अराजकता को सुंदर व्यवस्था में बदल देती है।`,
    health: `मन-शरीर संबंध आज आपका स्वास्थ्य विषय है। पोषण, दिनचर्या और निवारक देखभाल पर ध्यान दें।`,
    luckyNumber: 4, luckyColor: 'हरा', mood: 'केंद्रित',
  },
  Libra: {
    sign: 'Libra', symbol: '♎', dateRange: '23 सितंबर – 22 अक्टूबर', element: 'वायु', ruling: 'शुक्र',
    today: `आज हर बातचीत में सामंजस्य गूंज रहा है, तुला राशि। शुक्र आपके सामाजिक क्षेत्र को सौंदर्य और कूटनीति से आशीर्वादित करता है। आपका विरोधी शक्तियों के बीच सही संतुलन खोजने का उपहार आपको एक अपरिहार्य मध्यस्थ बनाता है।`,
    love: `साझेदारी आपका स्वाभाविक तत्व है, और आज यह विशेष चमक के साथ चमकती है। किसी खास के साथ बातचीत नई गहराई तक पहुँचती है।`,
    career: `आपकी कूटनीतिक कुशलता एक कार्यस्थल तनाव को सुलझाती है जिसे दूसरे असाध्य पाते हैं। कानूनी या अनुबंध संबंधी मामले आपके संतुलित दृष्टिकोण से लाभान्वित होते हैं।`,
    health: `सौंदर्य अनुष्ठान आज वास्तव में चिकित्सीय हैं। सक्रिय और पुनर्स्थापक गतिविधियों में संतुलन बनाएं।`,
    luckyNumber: 7, luckyColor: 'गुलाबी', mood: 'सामंजस्यपूर्ण',
  },
  Scorpio: {
    sign: 'Scorpio', symbol: '♏', dateRange: '23 अक्टूबर – 21 नवंबर', element: 'जल', ruling: 'प्लूटो',
    today: `आज रहस्य और परिवर्तन की गहराइयाँ आपको बुला रही हैं, वृश्चिक राशि। प्लूटो का प्रभाव उन छिपी सच्चाइयों को उजागर करता है जो दूसरों से अछूती रहीं। एक मनोवैज्ञानिक सफलता आपके जीवन के एक पुराने पैटर्न को बदल देती है।`,
    love: `आज तीव्रता आपकी प्रेम मुलाकातों को परिभाषित करती है। आत्मा की गहराई तक जुड़ाव ही आपको संतुष्ट करता है। साहसी संवेदनशीलता के ज़रिए विश्वास बनाएं।`,
    career: `अनुसंधान, जाँच और रणनीतिक योजना आपकी प्रतिभा के क्षेत्र हैं। आप वह उजागर करते हैं जो दूसरे छिपाते हैं — इस शक्ति का उपयोग नैतिक रूप से करें।`,
    health: `भावनात्मक प्रसंस्करण आपके लिए शारीरिक स्वास्थ्य है। डिटॉक्स अभ्यास — शाब्दिक और रूपक दोनों — आज विशेष रूप से प्रभावी हैं।`,
    luckyNumber: 8, luckyColor: 'गहरा लाल', mood: 'तीव्र',
  },
  Sagittarius: {
    sign: 'Sagittarius', symbol: '♐', dateRange: '22 नवंबर – 21 दिसंबर', element: 'अग्नि', ruling: 'बृहस्पति',
    today: `बृहस्पति का विस्तारकारी आशीर्वाद आज आपको संभावनाओं के दूर क्षितिज की ओर ले जाता है, धनु राशि। आपका दार्शनिक मन सत्य, ज्ञान और उन अनुभवों की भूख से भरा है जो आपकी सीमाओं को खींचते हैं। स्वतंत्रता आपका जन्मसिद्ध अधिकार है — इसका सम्मान करें।`,
    love: `आपका अदम्य उत्साह और संक्रामक हँसी अप्रत्याशित दिशाओं से प्रशंसकों को आकर्षित करती है। एक रिश्ता साझा रोमांच के माध्यम से गहरा होता है।`,
    career: `प्रकाशन, शिक्षण, यात्रा या अंतर-सांस्कृतिक उद्यम उत्कृष्ट रूप से अनुकूल हैं। आपकी आशावादिता और बड़ी सोच आपकी टीम को बड़े सपने देखने के लिए प्रेरित करती है।`,
    health: `बाहरी साहसिक कार्य और शारीरिक अन्वेषण आपकी आदर्श औषधि हैं। लेकिन अपनी सीमाएं जानें — यहाँ तक कि धनुर्धर को भी अपना धनुष आराम देना होता है।`,
    luckyNumber: 3, luckyColor: 'बैंगनी', mood: 'साहसी',
  },
  Capricorn: {
    sign: 'Capricorn', symbol: '♑', dateRange: '22 दिसंबर – 19 जनवरी', element: 'पृथ्वी', ruling: 'शनि',
    today: `शनि, आपका दृढ़ संरक्षक, आज आपकी अनुशासित धैर्य को ठोस प्रगति से पुरस्कृत करता है, मकर राशि। जो पर्वत आप लगातार चढ़ रहे थे, वह एक अद्भुत नया दृश्य प्रकट करता है। वरिष्ठ सहयोगी आपकी असाधारण दक्षता को पहचानते हैं।`,
    love: `आप वफ़ादारी और व्यावहारिक समर्पण के ज़रिए प्रेम व्यक्त करते हैं। आज संवेदनशीलता दिखाएं — यह गहरी आत्मीयता के लिए जगह बनाती है।`,
    career: `व्यावसायिक उपलब्धि आज विशेष रूप से उजागर है। जिस परियोजना में आपने महत्वपूर्ण प्रयास किया है उसे उच्चतम स्तर से मान्यता मिलती है।`,
    health: `हड्डियाँ, जोड़ और मुद्रा आज ध्यानपूर्वक देखभाल से लाभान्वित होते हैं। व्यायाम और पर्याप्त नींद को अपने महत्वाकांक्षी कार्यक्रम में शामिल करें।`,
    luckyNumber: 10, luckyColor: 'गहरा भूरा', mood: 'दृढ़',
  },
  Aquarius: {
    sign: 'Aquarius', symbol: '♒', dateRange: '20 जनवरी – 18 फरवरी', element: 'वायु', ruling: 'यूरेनस',
    today: `यूरेनस, महान जागृतिकर्ता, आज आपकी चेतना में प्रतिभा की चमक लाता है जो स्वयं आपको चकित कर देती है, कुंभ राशि। आपके मानवतावादी आदर्शों को अभिव्यक्ति का एक शक्तिशाली माध्यम मिलता है। भविष्य जो आप कल्पना करते हैं वह जितना दिखता है उससे कहीं अधिक निकट है।`,
    love: `मित्रता आपके गहरे रोमांटिक संबंधों की नींव है, और आज वह बंधन सुंदरता से मजबूत होता है। बौद्धिक संगतता आपके लिए अप्रतिरोध्य रूप से आकर्षक है।`,
    career: `प्रौद्योगिकी, नवाचार और मानवतावादी प्रयास आपकी प्रतिभा के क्षेत्र हैं। एक अपरंपरागत दृष्टिकोण वह हासिल करता है जो पारंपरिक तरीके नहीं कर सकते।`,
    health: `मानसिक उत्तेजना आपके लिए शारीरिक गतिविधि जितनी ही महत्वपूर्ण है। ऐसी गतिविधियों में संलग्न हों जो आपके असाधारण मन को चुनौती देते हुए आपके शरीर को भी हिलाएं।`,
    luckyNumber: 11, luckyColor: 'नीला', mood: 'अभिनव',
  },
  Pisces: {
    sign: 'Pisces', symbol: '♓', dateRange: '19 फरवरी – 20 मार्च', element: 'जल', ruling: 'नेप्च्यून',
    today: `नेप्च्यून, आपका रहस्यमय शासक, आज लोकों के बीच का पर्दा हटाता है, मीन राशि, जिससे असाधारण प्रेरणा आपके भीतर एक दिव्य नदी की तरह बहती है। आपका अंतर्ज्ञान इतना सूक्ष्म है कि आप वह महसूस करते हैं जो दूसरे अनुभव भी नहीं कर सकते।`,
    love: `आपकी रोमांटिक प्रकृति आज अपनी सबसे मनोरम अभिव्यक्ति तक पहुँचती है। एक स्वप्न जैसी मुलाकात में वास्तविक जादू की गुणवत्ता है।`,
    career: `रचनात्मक, उपचारात्मक, आध्यात्मिक और कलात्मक कार्य शानदार ढंग से फलते-फूलते हैं। आज विशुद्ध तार्किक विश्लेषण से अधिक प्रेरित अंतर्ज्ञान पर भरोसा करें।`,
    health: `आध्यात्मिक अभ्यास आपकी शारीरिक भलाई की आधारशिला है। पानी के पास ध्यान, पुनर्स्थापना योग, या गर्म स्नान आपकी संवेदनशील तंत्रिका प्रणाली को पुनर्जीवित करता है।`,
    luckyNumber: 12, luckyColor: 'समुद्री नीला', mood: 'स्वप्निल',
  },
};

export function getHoroscope(sign: string, lang: 'en' | 'hi' = 'en'): HoroscopeData | null {
  if (lang === 'hi') return horoscopesHi[sign] || null;
  return horoscopes[sign] || null;
}

export const ALL_SIGNS = Object.keys(horoscopes);
